name: devskim
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 37 7 * * 3
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  devskim:
    name: devskim
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@HEAD
      - name: analysis
        uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6 # ratchet:microsoft/DevSkim-Action@HEAD
      - name: upload
        uses: github/codeql-action/upload-sarif@1cd4d01d58f636bbdbffbfd3c121b3446d07e9f3 # ratchet:github/codeql-action/upload-sarif@HEAD
        with:
          sarif_file: devskim-results.sarif
