name: Publish Python 🐍 distribution 📦 to PyPI and GitHub Releases
on:
  release:
    types:
      - released
      - prereleased
jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@HEAD
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # ratchet:actions/setup-python@HEAD
        with:
          python-version: 3.12
      - name: Install poetry
        run: >-
          python3 -m
          pip install
          poetry
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m poetry build
      - name: Store the distribution packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@HEAD
        with:
          name: python-package-distributions
          path: dist/
  pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    needs:
      - build
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/belt-cli
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download dists
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317 # ratchet:actions/download-artifact@HEAD
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # ratchet:pypa/gh-action-pypi-publish@HEAD
  github-release:
    name: >-
      Sign the Python 🐍 distribution 📦 with Sigstore
      and upload them to GitHub Release
    needs:
      - build
    runs-on: ubuntu-24.04
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317 # ratchet:actions/download-artifact@HEAD
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@3605c8ce4e0c4c8ac7893b5caa6f5fbf934eff47 # ratchet:sigstore/gh-action-sigstore-python@HEAD
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          "$GITHUB_REF_NAME" dist/**
          --repo "$GITHUB_REPOSITORY"
  docker:
    name: Push Docker image to GitHub Container Registry 🐳
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@HEAD
      - name: Log in to the Container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # ratchet:docker/login-action@HEAD
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # ratchet:docker/metadata-action@HEAD
        with:
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # ratchet:docker/build-push-action@HEAD
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation for GitHub
        uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # ratchet:actions/attest-build-provenance@HEAD
        with:
          subject-name: ghcr.io/synmux/yt-pdlp
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
